# Generated by Django 5.2.6 on 2025-10-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название скидки')),
                ('type', models.CharField(max_length=25, verbose_name='Тип скидки')),
                ('value', models.FloatField(verbose_name='Размер скидки')),
                ('start_date', models.DateField(verbose_name='Начальная дата')),
                ('end_date', models.DateField(verbose_name='Конечная дата')),
            ],
            options={
                'verbose_name': 'Название скидки',
                'verbose_name_plural': 'Названия скидок',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия пользователя')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('bio', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Состав')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.categories')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Дата оформления')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.users')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Дата оформления')),
                ('status', models.CharField(max_length=25, verbose_name='Статус')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Способ оплаты')),
                ('customer_name', models.CharField(max_length=30, verbose_name='Имя покупателя')),
                ('total_amount', models.FloatField(verbose_name='Сумма заказа')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.users')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile_app.users')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
