# Generated by Django 5.2.6 on 2025-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия пользователя')),
                ('birthday', models.IntegerField(verbose_name='Номер телефона')),
                ('bio', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_author',
        ),
        migrations.AddField(
            model_name='book',
            name='id_user',
            field=models.ManyToManyField(to='exile_app.users'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
